name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build app for release
    runs-on: ubuntu-latest

#     container:
#       image:  google/dart:latest

    steps:
#     - uses: actions/checkout@v2
      
#     - name: Install dependencies
#       run: flutter pub get
      
#     - name: Run tests
#       run: pub run test
    
#     - name: Release apk
#       run: flutter build apk --release

    - name: setup-flutter
      uses: takuyaohashi/setup-flutter@v1
