name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build app for release
    runs-on: ubuntu-latest

#     container:
#       image:  google/dart:latest

    steps:
#     - name: Install dependencies
#       run: flutter pub get
      
#     - name: Run tests
#       run: pub run test
    
#     - name: Release apk
#       run: flutter build apk --release

#     - name: Flutter action
#       uses: subosito/flutter-action@v1.2.0


#     - name: install dependencies
#       uses: steebchen/flutter@v1.0.0
#       with:
#         args: pub get

#     - name: run tests
#       uses: steebchen/flutter@v1.0.0
#       with:
#         args: test

#     - name: build apk
#       uses: steebchen/flutter@v1.0.0
#       with:
#         args: build apk --release

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Flutter CLI
      uses: steebchen/flutter@v1.0.0
#       with:
#         args: build apk --release
      
#     - name: Flutter action
#       uses: subosito/flutter-action@v1.2.0
    - run: flutter build apk --debug --split-per-abi
